#%RAML 1.0 NamedExample
queue-a:
  {
"stop_id": 99871,

"stop_short": "GV-CENT",

"stop_type": "C",

"names": {

"commercial": "Gran Via Central",

"long": "Parada Gran Via Central, Madrid"

},

"geo": {

"lat": "40.420123",

"lng": "-3.705456"

},

"enabled": "Y",

"audit": {

"source": "LEGACY_SYS",

"created": "2024-10-01"

  }
}